### ISSUE TITLE
Use Aikar Java Flags for Paper MC

### ISSUE THREAD

**Issue by Cool-Cole** [Yot360/mc-server-python#1]
The flags can be found here -> https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

These flags fine tune Java's garbage collector and are recommended for paper MC servers. They cause a large performance increase and are recommend.

You are probably going to want to replace "-Xms10G -Xmx10G" with "-Xms4G -Xmx4G" as 10 gigabytes is probably to much for most PCs.

**Comment by Yot360** [comment]
Nice, I will add another option like "More optimized start.sh file", to let users select which start.sh file they want.

**Comment by Yot360** [comment]
Ok, done I updated the script like I said earlier, and fixed some issues that happened while editing vanilla files.
