### ISSUE TITLE
Redundant Folder Structure

### ISSUE THREAD

**Issue by JohnnyIrvin** [Yot360/mc-server-python#10]
# Description

It seems that the folder structure is redundant. We have an extra folder called "src" between the first module of python code, and the other general purpose files.

# Suggested Fix

Remove redundant file structure.

**Comment by peterHoburg** [comment]
This is a hotly debated topic right now. Poetry suggests not having a src folder, but supports it. The official docs suggest having a src folder. 

https://packaging.python.org/tutorials/packaging-projects/

Having a src dir makes it easy to navigate projects even if it is your first time seeing them. src also allows you to have multiple packages in the same structure with no changes.

**Comment by JohnnyIrvin** [comment]
@peterHoburg As I'm not overly familiar with the packaging documentation, I'll leave it for the project maintainer(s) to decide.

**Comment by peterHoburg** [comment]
I made the PR to turn it into a pypi package. It follows most/all of the package best practices. 

The pyproject.toml pep can't come soon enough. The python packaging ecosystem is kind of a mess right now.

**Comment by JohnnyIrvin** [comment]
@peterHoburg I'm good with what is in place then.
