### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by peterHoburg** [Yot360/mc-server-python#12]
When you push code changes (not just readme)  make sure to iterate `version = 0.2.1` in `setup.cfg`. Try to follow [semantic versioning](https://semver.org/). 

When you make a new release with the code changes put the same version in the `Release Tag version` section as in `setup.cfg`. You should also include `v0.2.1` before the text in the `Release title`. It makes it easier to tell what version the package is on in github and pypi.

**Comment by JohnnyIrvin** [comment]
The packaging documentation, specifically for versioning, is also helpful.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#version

**Comment by Yot360** [comment]
> When you push code changes (not just readme)  make sure to iterate `version = 0.2.1` in `setup.cfg`. Try to follow [semantic versioning](https://semver.org/). 
> 
> 
> 
> When you make a new release with the code changes put the same version in the `Release Tag version` section as in `setup.cfg`. You should also include `v0.2.1` before the text in the `Release title`. It makes it easier to tell what version the package is on in github and pypi. 

Thank you, I added 1.2.1 to the setup.cfg file since it's the latest release.
