### ISSUE TITLE
Undefined Path

### ISSUE THREAD

**Issue by JohnnyIrvin** [Yot360/mc-server-python#4]
# Description of Issue
Path is never defined during invalid input.

# Reproduction Steps
1. Run the application.
2. Enter an invalid input.
3. Receive error.

```
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    os.chdir(path)
NameError: name 'path' is not defined
```

# Bug Location
https://github.com/Yot360/mc-server-python/blob/4305a70ab8335f86ae24bb44ca154f86f472ae19/main.py#L56

# Suggested Solutions
1. Use a while loop.

**Comment by Yot360** [comment]
Thanks for the feedback, so if I understand you want the question to be asked again when the entered number is invalid?

**Comment by JohnnyIrvin** [comment]
~~@Yot360 I fix it with this -> https://github.com/Yot360/mc-server-python/pull/7~~

**Comment by JohnnyIrvin** [comment]
@Yot360 Seems you updated faster than I could create a pull request --- heres a new one https://github.com/Yot360/mc-server-python/pull/8

**Comment by JohnnyIrvin** [comment]
@Yot360 Thank you for merging this! :dancers:
