### ISSUE TITLE
Unused Import

### ISSUE THREAD

**Issue by JohnnyIrvin** [Yot360/mc-server-python#5]
# Description of Issue
Subprocess is never used.

# Reproduction Steps
1. Search for uses `grep -in subprocess main.py`
2. Receive response
```
4:import subprocess
```

# Bug Location
https://github.com/Yot360/mc-server-python/blob/4305a70ab8335f86ae24bb44ca154f86f472ae19/main.py#L4

# Suggested Solutions
1. Remove

**Comment by Yot360** [comment]
I actually added it for next update (make the script work better with windows). But I can remove it for this version and re-add it later.

**Comment by JohnnyIrvin** [comment]
> I actually added it for next update (make the script work better with windows). But I can remove it for this version and re-add it later.

I've also implemented this here https://github.com/Yot360/mc-server-python/pull/7

**Comment by JohnnyIrvin** [comment]
> I actually added it for next update (make the script work better with windows). But I can remove it for this version and re-add it later.

Works for me.

**Comment by Yot360** [comment]
> > I actually added it for next update (make the script work better with windows). But I can remove it for this version and re-add it later.
> 
> Works for me.

What doesn't work is the sh script, since windows uses bat script.
But I removed the import.
